### PR TITLE
switch off curly rule

### PR DESCRIPTION
**Pull request by formatlos**
I've added the curly rule to also be off, as it might conflict with eslint

### CODE REVIEW

**Comment by lydell** [comment]
How can it conflict?

**Comment by formatlos** [comment]
if you're using the `multi-line` option for the `curly` rule, which is for example the default in eslint-config-airbnb, the following would result in an eslint error

```
/*eslint curly: ["error", "multi-line"]*/

if (foo)
  doSomething();
else
  doSomethingElse();
```
prettier would wrap into a new line, if the line gets to long and therefore end up in an eslint-error

**Comment by lydell** [comment]
I see! Nice example!

The `curly` rule is still very useful for those who would like to enforce that curlies are always used with `if`s and suchlike – the `"all"` option.

Would you like to update your PR add `curly` as a [special rule](https://github.com/prettier/eslint-config-prettier#special-rules) instead? If you do, don’t forget to run `npm test` to verify that you got it all right.

**Comment by lydell** [comment]
Thanks!

**Comment by lydell** [comment]
Released in v1.6.0.

**Pull request merged**
