### PR TITLE
add rule `@typescript/lines-around-comment`

### PR DESCRIPTION
**Pull request by ttionya**
[`@typescript-eslint/eslint-plugin@5.55.0`](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.55.0) added new rule [`@typescript-eslint/lines-around-comment`](https://typescript-eslint.io/rules/lines-around-comment/).

### CODE REVIEW

**Comment by DannyNemer** [comment]
Would love to see this merged! 🙏

**Comment by lydell** [comment]
Released in v8.8.0. Thanks!

**Comment by DannyNemer** [comment]
Thank you!

**Comment by Webbrother** [comment]
image

Why this was added? It is strongly recommended do not use.

**Pull request merged**
