### PR TITLE
chore: migrate to changeset for automatically releasing

### LINKED ISSUE #277: maintenance: use `changesets` for releasing automatically
related #275

### PR DESCRIPTION
**Pull request by JounQin**
close #277

### CODE REVIEW

**Comment by lydell** [comment]
Hi!

I don’t want to review. I trust you with this stuff.

Btw, if you wondered what package-real.json was for: I got obsessed with making npm packages smaller, so I generated a smaller package.json without all the crap that doesn’t matter in an npm package (scripts, devDependencies). That’s also why I truncated the readme file – I personally never read readmes on npmjs.com since they are always out of date. eslint-config-prettier has a lot of downloads, so we quickly reach terabytes of wasted bytes. (I didn’t minify the code, since that makes debugging and auditing harder.) But these things are up to you now.

**Comment by JounQin** [comment]
@lydell I know what does the `real` file do, I've changed to use `clean-pkg-json` for this purpose.

**Comment by lydell** [comment]
Thanks for sharing [clean-pkg-json](https://github.com/privatenumber/clean-pkg-json)! Looks great.

Regarding the readme: I find it kind of ironic that the readme is almost twice as big as `index.js` + `bin/*` 😄 But again, it’s up to you.

**Comment by JounQin** [comment]
I'll merge this PR as-is then.

**Review by Scutua — APPROVED** [review]

**Pull request merged**
